version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db                # Reference to the MySQL service in Docker
      DB_PORT: 3306
      DB_DATABASE: bookStore
      DB_USERNAME: root
      DB_PASSWORD: ""
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""       # Same as DB_PASSWORD in .env
      MYSQL_DATABASE: bookStore     # Your database name
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db                 # Service name for MySQL
      PMA_USER: root
      PMA_PASSWORD: ""
    depends_on:
      - db

volumes:
  mysql-data:
